
--=======================================================
--  This code is generated by Terasic System Builder
--=======================================================
library ieee;
use ieee.std_logic_1164.all;
use IEEE.numeric_std.all;
use work.My_lib.all;

Entity DE2_115 is
	port(
--		/** On-board pheripheral**/
  
		CLOCK_50	 								: 		in std_logic; 									--		/* CLOCKs */
		LEDG										:		out std_logic_vector(8 downto 0);		--		/* LEDs */
		LEDR										:		out std_logic_vector(17 downto 0);
		KEY										:		in std_logic_vector(3 downto 0);			--		/* KEYs */
		SW											:		in std_logic_vector(17 downto 0);		--		/* SWITCHEs */
		HEX0, HEX1, HEX2, HEX3				:		out std_logic_vector(6 downto 0);		--		/* 7-SEGMENTS */
		HEX4, HEX5, HEX6, HEX7				:		out std_logic_vector(6 downto 0));	
   end DE2_115;
		
-- Architecture
architecture DE2_115_arch of DE2_115 is
	signal ledg_vir							:	   std_logic_vector(8 downto 0);      	-- LEDS
	signal ledr_vir							:		std_logic_vector(17 downto 0);	  
	signal key_vir								:		std_logic_vector(3 downto 0);			-- KEYS
	signal sw_vir								:		std_logic_vector(17 downto 0);  		-- SWITCHES
	signal hex0_vir, hex1_vir, hex2_vir :		std_logic_vector(6 downto 0);			-- 7SEG 
	signal hex3_vir, hex4_vir 				:		std_logic_vector(6 downto 0);
	signal hex5_vir, hex6_vir 				:		std_logic_vector(6 downto 0);
	signal hex7_vir							:		std_logic_vector(6 downto 0);


begin

L1: my_system_console port map(CLOCK_50,ledg_vir,ledr_vir,hex0_vir,hex1_vir,hex2_vir,hex3_vir,hex4_vir,hex5_vir, hex6_vir,hex7_vir,key_vir,sw_vir);
L2: user_logic port map(CLOCK_50,LEDG,LEDR,KEY,SW,HEX0,HEX1,HEX2,HEX3,HEX4,HEX5,HEX6,HEX7,ledg_vir,ledr_vir,key_vir,sw_vir,hex0_vir,hex1_vir,hex2_vir,hex3_vir,hex4_vir,hex5_vir,hex6_vir,hex7_vir);									  

end DE2_115_arch;

  
