
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module my_system_console(

	//////////// CLOCK //////////
	input 		          		CLOCK_50,

	//////////// LED //////////
	input		     [8:0]		ledg_vir,
	input		    [17:0]		ledr_vir,

	//////////// SEG7 //////////
	input		     [6:0]		hex0_vir,
	input		     [6:0]		hex1_vir,
	input		     [6:0]		hex2_vir,
	input		     [6:0]		hex3_vir,
	input		     [6:0]		hex4_vir,
	input		     [6:0]		hex5_vir,
	input		     [6:0]		hex6_vir,
	input		     [6:0]		hex7_vir,
	
	//////////// KEY //////////
	output 		     [3:0]		key_vir,

	//////////// SW //////////
	output 		    [17:0]		sw_vir
);



system_console_gui  system_console (
    /*input  wire        */    .clk_clk                             (CLOCK_50),
    /*input  wire        */    .reset_reset_n                       (1'b1),

    /*input  wire [8:0]  */    .pio_ledg_external_connection_export (ledg_vir),
    /*input  wire [17:0] */    .pio_ledr_external_connection_export (ledr_vir),

    /*input  wire [6:0]  */    .pio_hex0_external_connection_export (hex0_vir),
    /*input  wire [6:0]  */    .pio_hex1_external_connection_export (hex1_vir),
    /*input  wire [6:0]  */    .pio_hex2_external_connection_export (hex2_vir),
    /*input  wire [6:0]  */    .pio_hex3_external_connection_export (hex3_vir),
    /*input  wire [6:0]  */    .pio_hex4_external_connection_export (hex4_vir),
    /*input  wire [6:0]  */    .pio_hex5_external_connection_export (hex5_vir),
    /*input  wire [6:0]  */    .pio_hex6_external_connection_export (hex6_vir),
    /*input  wire [6:0]  */    .pio_hex7_external_connection_export (hex7_vir),


    /*output wire [3:0]  */    .pio_key_external_connection_export  (key_vir),
    /*output wire [17:0] */    .pio_sw_external_connection_export   (sw_vir)   

);


endmodule
